name: Go

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Test Go solutions
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: cd go-project-euler-100 && go test
